# Generated by Django 4.2.7 on 2023-11-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
