# Generated by Django 4.2.7 on 2023-11-18 05:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_filemetadata_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemetadata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='filemetadata',
            name='uuid',
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
